"""initial schema

Revision ID: e04d6cb7e618
Revises: 2313064ed1ef
Create Date: 2026-09-10 23:39:33.069888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04d6cb7e618'
down_revision = '2313064ed1ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_user_status', ['user_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_user_status')

    # ### end Alembic commands ###
